---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'
rvm:
  - 1.9.3
  - 2.1.0
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"
matrix:
  include:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
notifications:
  email: false
